version: "3.9"

services:
  db:
    restart: always
    build:
      context: ./postgree_db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fake_gaspar

  projeto_php:
    container_name: php
    image: php
    restart: always
    build:
      context: ./projeto_php
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:80"

  projeto_python_app:
    restart: always
    build:
      context: ./projeto_python/app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DEV_ENV=${DEV_ENV}
      - TEST_ENV=${TEST_ENV}
      - COMPOSER=True
    links:
      - projeto_fake_gaspar
  
  projeto_fake_gaspar:
    restart: always
    build:
      context: ./projeto_python/fake_gaspar
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${MINHA_KEY_NO_ENV}
      # - DATABASE_URL_ENDPOINT=postgresql://postgres:postgres@db:5432/fake_gaspar
      - DATABASE_URL_ENDPOINT=sqlite+pysqlite:///foo.db
    volumes:
      - type: bind
        source: ./bind_mounts/fake_gaspar
        target: /code/app_logs
    depends_on:
      - db

  pgadmin:
    restart: always
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=t@t.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db